// seeder.js
const mongoose = require("mongoose");
const dotenv = require("dotenv");
const path = require("path");
const Hotel = require("./models/Hotel");
const Food = require("./models/Food");
const connectDB = require("./config/db"); // your db connection file

dotenv.config();
connectDB();

const hotels = [

  {
    name: "Golden Spice",
    address: "MG Road",
    city: "Thodupuzha",
    state: "Kerala",
    pincode: "560001",
    contact: "+91 9876543210",
    image: "/uploads/hotelimages/Golden-Spice.jpg",
    rating: 4.6,
  },
  {
    name: "Royal Tandoor",
    address: "Park Street",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700016",
    contact: "+91 9123456780",
    image: "/uploads/hotelimages/Royal-Tandoor.jpg",
    rating: 4.4,
  },
  {
    name: "Spicy Treats",
    address: "Anna Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600040",
    contact: "+91 9865321470",
    image: "/uploads/hotelimages/Spicy-Treats.jpg",
    rating: 4.3,
  },
  {
    name: "Urban Biryani House",
    address: "Charminar",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500002",
    contact: "+91 9012345678",
    image: "/uploads/hotelimages/UrbanBiryani-House.jpg",
    rating: 4.7,
  },
  {
    name: "Seafood Bay",
    address: "Marine Drive",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400020",
    contact: "+91 9223344556",
    image: "/uploads/hotelimages/Seafood-Bay.jpg",
    rating: 4.5,
  },
  {
    name: "North Spice Hub",
    address: "Sector 18",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201301",
    contact: "+91 9988776655",
    image: "/uploads/hotelimages/NorthSpice-Hub.jpg",
    rating: 4.2,
  },
  {
    name: "Desi Zaika",
    address: "Connaught Place",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110001",
    contact: "+91 9001122334",
    image: "/uploads/hotelimages/Desi-Zaika.jpg",
    rating: 4.8,
  },
  {
    name: "Punjabi Rasoi",
    address: "Sector 17",
    city: "Chandigarh",
    state: "Punjab",
    pincode: "160017",
    contact: "+91 9090808070",
    image: "/uploads/hotelimages/Punjabi-Rasoi.jpg",
    rating: 4.4,
  },
  {
    name: "Veggie Delight",
    address: "Paldi",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380007",
    contact: "+91 9334455667",
    image: "/uploads/hotelimages/Veggie-Delight.jpg",
    rating: 4.1,
  },
  {
    name: "Kerala Flavours",
    address: "Fort Kochi",
    city: "Kochi",
    state: "Kerala",
    pincode: "682001",
    contact: "+91 9445566778",
    image: "/uploads/hotelimages/Kerala-Flavours.jpg",
    rating: 4.6,
  },
  {
    name: "Malabar Delights",
    address: "Calicut Beach Road",
    city: "Kozhikode",
    state: "Kerala",
    pincode: "673032",
    contact: "+91 9847012345",
    image: "/uploads/hotelimages/Malabar-Delights.jpg",
    rating: 4.7,
  },
  {
    name: "Seaside Spice",
    address: "Lighthouse Road",
    city: "Kovalam",
    state: "Kerala",
    pincode: "695527",
    contact: "+91 9895123456",
    image: "/uploads/hotelimages/Seaside-Spice.jpg",
    rating: 4.5,
  },
  {
    name: "Toddy Shop Taste",
    address: "Kumarakom Backwaters",
    city: "Kottayam",
    state: "Kerala",
    pincode: "686563",
    contact: "+91 9746123456",
    image: "/uploads/hotelimages/ToddyShop-Taste.jpg",
    rating: 4.4,
  },
  {
    name: "Backwater Treats",
    address: "Alleppey Houseboats",
    city: "Alappuzha",
    state: "Kerala",
    pincode: "688001",
    contact: "+91 9947123456",
    image: "/uploads/hotelimages/Backwater-Treats.jpg",
    rating: 4.8,
  },
  {
    name: "Chaya Kada",
    address: "MG Road",
    city: "Thrissur",
    state: "Kerala",
    pincode: "680001",
    contact: "+91 9072123456",
    image: "/uploads/hotelimages/Chaya-Kada.jpg",
    rating: 4.3,
  },
];



const foods = [
  {
    name: "Grilled Chicken Sandwich",
    description: "Juicy grilled chicken with lettuce, tomato, and mayo served on toasted bread.",
    price: 480,
    stock: 25,
    image: "/uploads/foodimages/grilled-chicken-sandwich.jpg",
    hotelName: "Backwater Treats",
  },
  {
    name: "Classic Caesar Salad",
    description: "Crisp romaine lettuce with parmesan, croutons, and Caesar dressing.",
    price: 350,
    stock: 30,
    image: "/uploads/foodimages/caesar-salad.jpg",
    hotelName: "Backwater Treats",
  },
  {
    name: "Veggie Pasta Alfredo",
    description: "Penne pasta tossed in creamy Alfredo sauce with fresh vegetables.",
    price: 500,
    stock: 20,
    image: "/uploads/foodimages/veggie-pasta-alfredo.jpg",
    hotelName: "Backwater Treats",
  },
  {
    name: "Kerala Style Prawn Roast",
    description: "Spicy prawns roasted with traditional Kerala masala and coconut oil.",
    price: 250,
    stock: 15,
    image: "/uploads/foodimages/kerala-prawn-roast.jpg",
    hotelName: "Toddy Shop Taste",
  },
  {
    name: "Beef Fry Kerala Style",
    description: "Tender beef pieces sautéed with black pepper, curry leaves, and spices.",
    price: 220,
    stock: 20,
    image: "/uploads/foodimages/beef-fry.jpg",
    hotelName: "Toddy Shop Taste",
  },
  {
    name: "Fish Pollichathu",
    description: "Marinated fish wrapped in banana leaf and grilled with spices.",
    price: 280,
    stock: 12,
    image: "/uploads/foodimages/fish-pollichathu.jpg",
    hotelName: "Toddy Shop Taste",
  },
  {
    name: "Crab Masala",
    description: "Fresh crab cooked in a spicy and tangy Kerala-style masala gravy.",
    price: 320,
    stock: 12,
    image: "/uploads/foodimages/crab-masala.jpg",
    hotelName: "Seaside Spice",
  },
  {
    name: "Calamari Fry",
    description: "Tender squid rings marinated with spices and deep-fried to golden perfection.",
    price: 220,
    stock: 18,
    image: "/uploads/foodimages/calamari-fry.jpg",
    hotelName: "Seaside Spice",
  },
  {
    name: "Fish Curry Rice",
    description: "Spicy coastal fish curry served with steamed rice, a traditional seaside delight.",
    price: 250,
    stock: 20,
    image: "/uploads/foodimages/fish-curry-rice.jpg",
    hotelName: "Seaside Spice",
  },
  {
    name: "Chilli Chicken",
    description: "Crispy chicken tossed in a spicy and tangy sauce with bell peppers and onions.",
    price: 220,
    stock: 20,
    image: "/uploads/foodimages/chilli-chicken.jpg",
    hotelName: "Spicy Treats",
  },
  {
    name: "Paneer Chilli",
    description: "Soft paneer cubes stir-fried with spicy chilli sauce and crunchy vegetables.",
    price: 180,
    stock: 18,
    image: "/uploads/foodimages/paneer-chilli.jpg",
    hotelName: "Spicy Treats",
  },
  {
    name: "Spicy Prawn Fry",
    description: "Succulent prawns marinated in hot spices and shallow-fried for a fiery flavor.",
    price: 250,
    stock: 15,
    image: "/uploads/foodimages/spicy-prawn-fry.jpg",
    hotelName: "Spicy Treats",
  },
  {
    name: "Butter Naan",
    description: "Soft, fluffy naan baked in the tandoor and brushed with melted butter.",
    price: 50,
    stock: 50,
    image: "/uploads/foodimages/butter-naan.jpg",
    hotelName: "Royal Tandoor",
  },
  {
    name: "Chicken Tikka Masala",
    description: "Grilled chicken pieces cooked in a creamy, spiced tomato-based gravy.",
    price: 240,
    stock: 20,
    image: "/uploads/foodimages/chicken-tikka-masala.jpg",
    hotelName: "Royal Tandoor",
  },
  {
    name: "Chicken Seekh Kebab",
    description: "Minced chicken mixed with aromatic spices, shaped onto skewers, and grilled in the tandoor.",
    price: 220,
    stock: 15,
    image: "/uploads/foodimages/chicken-seekh-kebab.jpg",
    hotelName: "Royal Tandoor",
  },
  {
    name: "Malabar Fish Biryani",
    description: "Fragrant basmati rice cooked with marinated fish and authentic Malabar spices.",
    price: 300,
    stock: 15,
    image: "/uploads/foodimages/malabar-fish-biryani.jpg",
    hotelName: "Malabar Delights",
  },
  {
    name: "Kerala Chicken Curry with Rice",
    description: "Spicy and flavorful chicken curry served with steamed Kerala red rice.",
    price: 220,
    stock: 20,
    image: "/uploads/foodimages/kerala-chicken-curry.jpg",
    hotelName: "Malabar Delights",
  },
  {
    name: "Lucknowi Chicken Biryani",
    description: "Fragrant basmati rice cooked with tender chicken and subtle Awadhi spices for a royal taste.",
    price: 250,
    stock: 20,
    image: "/uploads/foodimages/lucknowi-chicken-biryani.jpg",
    hotelName: "Urban Biryani House",
  },
  {
    name: "Mutton Biryani",
    description: "Slow-cooked tender mutton pieces mixed with spiced rice, served with raita.",
    price: 280,
    stock: 15,
    image: "/uploads/foodimages/mutton-biryani.jpg",
    hotelName: "Urban Biryani House",
  },
  {
    name: "Paneer Biryani",
    description: "A vegetarian biryani with paneer cubes, mixed vegetables, and aromatic spices.",
    price: 200,
    stock: 18,
    image: "/uploads/foodimages/paneer-biryani.jpg",
    hotelName: "Urban Biryani House",
  },
   {
    name: "Rogan Josh",
    description: "A rich and aromatic Kashmiri-style lamb curry cooked with yogurt and spices.",
    price: 270,
    stock: 15,
    image: "/uploads/foodimages/rogan-josh.jpg",
    hotelName: "North Spice Hub",
  },
  {
    name: "Amritsari Kulcha with Chole",
    description: "Fluffy stuffed kulcha bread served with spicy chickpea curry and pickles.",
    price: 160,
    stock: 22,
    image: "/uploads/foodimages/amritsari-kulchaa.jpg",
    hotelName: "North Spice Hub",
  },
  {
    name: "Shahi Paneer",
    description: "Paneer cubes cooked in a royal creamy gravy made with cashews and saffron.",
    price: 190,
    stock: 20,
    image: "/uploads/foodimages/shahi-paneer.jpg",
    hotelName: "North Spice Hub",
  },
  {
    name: "Tandoori Chicken",
    description: "Juicy chicken marinated in yogurt and spices, roasted in a traditional clay oven.",
    price: 250,
    stock: 18,
    image: "/uploads/foodimages/tandoori-chicken.jpg",
    hotelName: "Punjabi Rasoi",
  },
  {
    name: "Lassi (Sweet or Salted)",
    description: "Refreshing Punjabi yogurt-based drink, served sweet or salted in a traditional tall glass.",
    price: 90,
    stock: 30,
    image: "/uploads/foodimages/lassi.jpg",
    hotelName: "Punjabi Rasoi",
  },
  {
    name: "Amritsari Fish Fry",
    description: "Crispy deep-fried fish marinated with authentic Amritsari spices, served with chutney.",
    price: 220,
    stock: 15,
    image: "/uploads/foodimages/amritsari-fish.jpg",
    hotelName: "Punjabi Rasoi",
  },
  {
    name: "Paneer Butter Masala",
    description: "Soft paneer cubes simmered in a rich, buttery tomato-based gravy with aromatic spices.",
    price: 180,
    stock: 20,
    image: "/uploads/foodimages/Paneer-Butter-Masala.jpg",
    hotelName: "Veggie Delight",
  },
  {
    name: "Veg Biryani",
    description: "Fragrant basmati rice cooked with assorted vegetables, saffron, and traditional spices.",
    price: 150,
    stock: 25,
    image: "/uploads/foodimages/Veg-Biryani.jpg",
    hotelName: "Veggie Delight",
  },
  {
    name: "Mushroom Do Pyaza",
    description: "Button mushrooms stir-fried with double the onions and Indian spices for a tangy flavor.",
    price: 160,
    stock: 18,
    image: "/uploads/foodimages/Mushroom-Do-Pyaza.jpg",
    hotelName: "Veggie Delight",
  },
  {
    name: "Chettinad Chicken Curry",
    description: "Spicy and aromatic chicken curry cooked with freshly ground Chettinad masala.",
    price: 220,
    stock: 15,
    image: "/uploads/foodimages/ChettinadChicken-Curry.jpg",
    hotelName: "Desi Zaika",
  },
  {
    name: "Kothu Parotta",
    description: "Layered parotta shredded and stir-fried with eggs, meat, and spicy masala.",
    price: 150,
    stock: 20,
    image: "/uploads/foodimages/Kothu-Parotta.jpg",
    hotelName: "Desi Zaika",
  },
  {
    name: "Fish Fry (Vanjaram Meen Varuval)",
    description: "Seer fish marinated in South Indian spices and shallow-fried to perfection.",
    price: 180,
    stock: 12,
    image: "/uploads/foodimages/Fish-Fry.jpg",
    hotelName: "Desi Zaika",
  },
  {
    name: "Pongal with Vada",
    description: "Traditional Tamil breakfast dish made of rice and lentils, served with crispy vada.",
    price: 120,
    stock: 25,
    image: "/uploads/foodimages/Pongalwith-Vada.jpg",
    hotelName: "Desi Zaika",
  },

  {
    name: "Grilled Lobster Tail",
    description: "Fresh lobster tail grilled to perfection with garlic butter and herbs.",
    price: 700,
    stock: 10,
    image: "/uploads/foodimages/GrilledLobster-Tail.jpg",
    hotelName: "Seafood Bay",
  },
  {
    name: "Garlic Butter Prawns",
    description: "Succulent prawns sautéed in garlic butter and served with lemon wedges.",
    price: 600,
    stock: 20,
    image: "/uploads/foodimages/GarlicButter-Prawns.jpg",
    hotelName: "Seafood Bay",
  },
  {
    name: "Baked Salmon Fillet",
    description: "Tender salmon fillet baked with herbs and served with a side of veggies.",
    price: 1500,
    stock: 15,
    image: "/uploads/foodimages/BakedSalmon-Fillet.jpg",
    hotelName: "Seafood Bay",
  },
  {
    name: "Kuzhi Mandhi",
    description: "Aromatic Kerala-style dum biryani, rich with spices and tender meat",
    price: 250,
    stock: 20,
    image: "/uploads/foodimages/Kuzhi-Mandhi.jpg",
    hotelName: "Golden Spice",
  },
  {
    name: "Butter Chicken",
    description: "Rich creamy tomato gravy with tender chicken pieces",
    price: 320,
    stock: 15,
    image: "/uploads/foodimages/Butter-chicken.jpg",
    hotelName: "Golden Spice",
  },
  {
    name: "Paneer Tikka",
    description: "Char-grilled paneer cubes with spicy marination",
    price: 250,
    stock: 20,
    image: "/uploads/foodimages/paneer-tika.jpg",
    hotelName: "Royal Tandoor",
  },
  {
    name: "Hyderabadi Biryani",
    description: "Fragrant basmati rice cooked with saffron and chicken",
    price: 350,
    stock: 25,
    image: "/uploads/foodimages/Hyderabadi-Biryani.jpg",
    hotelName: "Urban Biryani House",
  },
  {
    name: "Masala Dosa",
    description: "South Indian crispy dosa stuffed with spiced potatoes",
    price: 180,
    stock: 30,
    image: "/uploads/foodimages/Masala-Dosa.jpg",
    hotelName: "Spicy Treats",
  },
  {
    name: "Fish Curry",
    description: "Authentic coastal style fish curry in coconut gravy",
    price: 400,
    stock: 10,
    image: "/uploads/foodimages/Fish-Curry.jpg",
    hotelName: "Seafood Bay",
  },
  {
    name: "Chole Bhature",
    description: "Spicy chickpeas with fluffy deep-fried bread",
    price: 150,
    stock: 40,
    image: "/uploads/foodimages/Chole-Bhature.jpg",
    hotelName: "North Spice Hub",
  },
  {
    name: "Dal Makhani",
    description: "Slow-cooked black lentils in buttery gravy",
    price: 220,
    stock: 18,
    image: "/uploads/foodimages/Dal-Makhani.jpg",
    hotelName: "Malabar Delights",
  },
  {
    name: "Amritsari Kulcha",
    description: "Stuffed kulcha bread with butter and pickle",
    price: 200,
    stock: 12,
    image: "/uploads/foodimages/Amritsari-Kulcha.jpg",
    hotelName: "Punjabi Rasoi",
  },
  {
    name: "Gujarati Thali",
    description: "Traditional Gujarati meal with dal, rice, rotis, and sabzis",
    price: 300,
    stock: 10,
    image: "/uploads/foodimages/Gujarati-Thali.jpg",
    hotelName: "Veggie Delight",
  },
  {
    name: "Kerala Sadya",
    description: "Banana leaf traditional feast with multiple curries",
    price: 450,
    stock: 8,
    image: "/uploads/foodimages/Kerala-Sadya.jpg",
    hotelName: "Kerala Flavours",
  },
  {
    name: "Appam & Stew",
    description: "Soft hoppers served with coconut milk-based vegetable stew",
    price: 150,
    stock: 20,
    image: "/uploads/foodimages/Appam-Stew.jpg",
    hotelName: "Kerala Flavours",
  },
  {
    name: "Puttu & Kadala Curry",
    description: "Steamed rice cake with spicy black chickpea curry",
    price: 120,
    stock: 25,
    image: "/uploads/foodimages/PuttuKadala-Curry.jpg",
    hotelName: "Kerala Flavours",
  },
  {
    name: "Kerala Parotta & Beef Curry",
    description: "Flaky layered parotta with spicy slow-cooked beef curry",
    price: 260,
    stock: 18,
    image: "/uploads/foodimages/KeralaParottaBeef-Curry.jpg",
    hotelName: "Golden Spice",
  },
  {
    name: "Karimeen Pollichathu",
    description: "Pearl spot fish marinated and roasted in banana leaf",
    price: 340,
    stock: 12,
    image: "/uploads/foodimages/Karimeen-Pollichathu.jpg",
    hotelName: "Malabar Delights",
  },
  {
    name: "Fish Moilee",
    description: "Fish curry with coconut milk, curry leaves, and mild spices",
    price: 280,
    stock: 15,
    image: "/uploads/foodimages/Fish-Moilee.jpg",
    hotelName: "Seaside Spice",
  },
  {
    name: "Malabar Chicken Biryani",
    description: "Thalassery-style aromatic chicken biryani",
    price: 300,
    stock: 20,
    image: "/uploads/foodimages/MalabarChicken-Biryani.jpg",
    hotelName: "Golden Spice",
  },
  {
    name: "Erachi Ularthiyathu",
    description: "Spicy Kerala-style beef fry with coconut slices",
    price: 280,
    stock: 16,
    image: "/uploads/foodimages/Erachi-Ularthiyathu.jpg",
    hotelName: "Toddy Shop Taste",
  },
  {
    name: "Meen Curry",
    description: "Tangy red fish curry with kokum and spices",
    price: 240,
    stock: 22,
    image: "/uploads/foodimages/Meen-Curry.jpg",
    hotelName: "Backwater Treats",
  },
  {
    name: "Vegetable Thoran",
    description: "Stir-fried vegetables with coconut and curry leaves",
    price: 110,
    stock: 30,
    image: "/uploads/foodimages/Vegetable-Thoran.jpg",
    hotelName: "Kerala Flavours",
  },
  {
    name: "Pazham Pori",
    description: "Golden fried banana fritters, a tea-time favorite",
    price: 90,
    stock: 35,
    image: "/uploads/foodimages/Pazham-Pori.jpg",
    hotelName: "Chaya Kada",
  },
  {
    name: "Parippu Vada",
    description: "Crispy lentil fritters, perfect with chutney",
    price: 50,
    stock: 40,
    image: "/uploads/foodimages/Parippu-Vada.jpg",
    hotelName: "Chaya Kada",
  },
];


const importData = async () => {
  try {
    // Clear existing data
    await Hotel.deleteMany();
    await Food.deleteMany();

    // Insert hotels
    const createdHotels = await Hotel.insertMany(hotels);

    // Map foods to correct hotel ObjectId
    const foodsWithHotelIds = foods
      .map((food) => {
        const hotel = createdHotels.find((h) => h.name === food.hotelName);
        if (!hotel) {
          console.warn(`⚠️ Hotel not found for food: ${food.name} (${food.hotelName})`);
          return null;
        }
        const { hotelName, ...rest } = food;
        return { ...rest, hotel: hotel._id };
      })
      .filter(Boolean); // remove nulls

    await Food.insertMany(foodsWithHotelIds);

    console.log("✅ Data Imported Successfully!");
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

importData();